<center><u><H1>KFold Cross Validation</H1></u></center>

In [2]:
from sklearn.model_selection import KFold
import numpy as np

In [3]:
X = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
y = np.array([11, 12, 13, 14])

In [4]:
kf = KFold(n_splits=2)

In [5]:
kf.get_n_splits(X)

2

In [6]:
print(kf)

KFold(n_splits=2, random_state=None, shuffle=False)


In [7]:
for train_index, test_index in kf.split(X):
    print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]

TRAIN: [2 3] TEST: [0 1]
TRAIN: [0 1] TEST: [2 3]


In [8]:
X_train

array([[1, 2],
       [3, 4]])

In [9]:
X_test

array([[5, 6],
       [7, 8]])

In [10]:
y_train

array([11, 12])

In [11]:
y_test

array([13, 14])

## Reference:

http://scikit-learn.org/stable/modules/generated/sklearn.model_selection.KFold.html