<center><u><H1>NUMPY</H1><u></center>   

In [1]:
import numpy as np

<b>Creating an array:</b>

In [2]:
arr = np.array([[0,1,2],[3,4,5],[6,7,8]])
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [3]:
ones = np.ones((2,3), dtype=int)
ones

array([[1, 1, 1],
       [1, 1, 1]])

In [4]:
rand = np.random.random((2,3))
rand

array([[0.29133591, 0.61632506, 0.51219075],
       [0.49574682, 0.09635554, 0.12194365]])

In [6]:
mu, sigma = 2, 0.5
v = np.random.normal(mu,sigma,100)
v

array([1.28279628, 2.06388299, 1.54657568, 2.45104566, 1.65682498,
       1.84648773, 2.2111714 , 2.65937227, 1.7263231 , 1.90204911,
       2.23188957, 2.11283505, 2.39635535, 1.95807135, 1.92039432,
       1.92985203, 2.23721309, 1.54570034, 1.37894616, 1.89060238,
       1.31750237, 2.01299631, 1.10723503, 1.88375678, 1.65129472,
       2.88836796, 1.61795613, 1.35149507, 2.38770792, 3.33859966,
       1.97301969, 2.02497047, 1.63784495, 1.67706655, 2.24582993,
       2.24894507, 1.97074381, 2.38616338, 1.98936552, 2.45163435,
       1.78354402, 2.04953812, 2.89417863, 2.12618592, 1.36595049,
       1.81457672, 1.88803194, 2.20760977, 2.63593137, 2.08139101,
       1.91072388, 1.5129478 , 1.21654079, 2.02402449, 2.58933728,
       1.13472551, 2.25051639, 1.76094905, 2.4779802 , 1.25698468,
       1.2535518 , 1.65914399, 2.13289909, 2.25795051, 1.77188288,
       2.2208402 , 1.68365786, 1.62559576, 2.83217274, 2.58266864,
       1.60411034, 1.75180811, 1.58297608, 2.18774323, 1.79195

<b>Check the attributes:</b>

In [5]:
arr.ndim

2

In [8]:
arr.shape

(3, 3)

In [9]:
arr.size

9

In [10]:
arr.dtype.name

'int64'

<H3>Mathematical Operations:</H3>

In [7]:
#Substraction
a = np.array([6,5,4,8])
b = np.array([1,2,5,10])
a-b

array([ 5,  3, -1, -2])

In [8]:
#Squaring an array
b**2

array([  1,   4,  25, 100])

In [9]:
#Applying trigonometic functions
np.sin(b)

array([ 0.84147098,  0.90929743, -0.95892427, -0.54402111])

In [14]:
#Conditional operations
b>1

array([False,  True,  True,  True])

In [15]:
#Unique values
values = [5,2,1,1,6,2,0,1]
np.unique(values)

array([0, 1, 2, 5, 6])

In [16]:
arr.sum(axis=0) 

array([ 9, 12, 15])

In [17]:
arr.sum(axis=1) 

array([ 3, 12, 21])

In [18]:
arr.min(axis=1)

array([0, 3, 6])

In [19]:
arr.cumsum(axis=0)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]])

In [20]:
# floor: returns the floor of each element
np.floor([0.5,1.1,-1.2,5,-2.0])

array([ 0.,  1., -2.,  5., -2.])

<h3>Indexing and slicing:</h3>

In [21]:
#Index positions
a = np.array([[3,4,5],[7,8,3],[0,3,23],[8,11,6]])
a.shape

(4, 3)

In [23]:
a[1,1]

np.int64(8)

In [24]:
a[0,0:2]

array([3, 4])

In [25]:
a[0,:]

array([3, 4, 5])

In [26]:
a[:,1]

array([ 4,  8,  3, 11])

In [27]:
a[:,-1]

array([ 5,  3, 23,  6])

### Iterating:

In [28]:
print(np.arange(5))

[0 1 2 3 4]


In [29]:
c = np.linspace(-2,2,20)
c

array([-2.        , -1.78947368, -1.57894737, -1.36842105, -1.15789474,
       -0.94736842, -0.73684211, -0.52631579, -0.31578947, -0.10526316,
        0.10526316,  0.31578947,  0.52631579,  0.73684211,  0.94736842,
        1.15789474,  1.36842105,  1.57894737,  1.78947368,  2.        ])

In [30]:
#The enumerate() function adds a counter to an iterable
y = [1, 1, 2, 2, 1, 1,3]
for index, item in enumerate(np.unique(y)):
    print(index, item+1)

0 2
1 3
2 4


In [31]:
for index, item in enumerate(np.arange(len(y))):
    print(index, item+1)

0 1
1 2
2 3
3 4
4 5
5 6
6 7


### Shape Manipulation:

In [32]:
# returns the array, flattened
a.ravel()

array([ 3,  4,  5,  7,  8,  3,  0,  3, 23,  8, 11,  6])

In [33]:
a.shape=(6,2)
a

array([[ 3,  4],
       [ 5,  7],
       [ 8,  3],
       [ 0,  3],
       [23,  8],
       [11,  6]])

In [34]:
a.transpose()

array([[ 3,  5,  8,  0, 23, 11],
       [ 4,  7,  3,  3,  8,  6]])

In [35]:
a.T.shape

(2, 6)

In [36]:
a.reshape(4,3)

array([[ 3,  4,  5],
       [ 7,  8,  3],
       [ 0,  3, 23],
       [ 8, 11,  6]])

In [37]:
# If a dimension is given as -1 in a reshaping operation, the other dimensions are automatically calculated
a.reshape(3,-1)

array([[ 3,  4,  5,  7],
       [ 8,  3,  0,  3],
       [23,  8, 11,  6]])

In [39]:
# The reshape function returns its argument with a modified shape, whereas the ndarray.resize method modifies the array itself:
b = np.array([[ 0.2,  18.,  20.,  4.],
       [ 41.,  15.,  11.,  10.],
       [ 0.5,  19.,  13.,  0.6]])
b.resize((2,6))

In [40]:
b

array([[ 0.2, 18. , 20. ,  4. , 41. , 15. ],
       [11. , 10. ,  0.5, 19. , 13. ,  0.6]])

In [41]:
#Floor: Return the floor of the input, element-wise
a = np.array([-1.7, -1.5, -0.2, 0.2, 1.5, 1.7, 2.0])
np.floor(a)

array([-2., -2., -1.,  0.,  1.,  1.,  2.])

In [42]:
# NEW AXIS
x1 = np.array([1, 2, 3, 4, 5])
x1_new = x1[:, np.newaxis]
x1_new

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [43]:
x2 = np.array([5, 4, 3])
x3 = x1_new + x2
x3

array([[ 6,  5,  4],
       [ 7,  6,  5],
       [ 8,  7,  6],
       [ 9,  8,  7],
       [10,  9,  8]])

In [44]:
x3_new = x3[:,np.newaxis,1]
x3_new

array([[5],
       [6],
       [7],
       [8],
       [9]])

## Stacking different arrays

In [47]:
c = np.floor(10*np.random.random((2,2)))
c

array([[9., 8.],
       [9., 0.]])

In [51]:
d = np.floor(10*np.random.random((2,2)))
d

array([[1., 9.],
       [3., 9.]])

In [52]:
# vstack: vertical aggregation
np.vstack((c,d))

array([[9., 8.],
       [9., 0.],
       [1., 9.],
       [3., 9.]])

In [53]:
# hstack: horizontal aggregation
np.hstack((c,d))

array([[9., 8., 1., 9.],
       [9., 0., 3., 9.]])

## Splitting arrays

In [54]:
hs = np.floor(10*np.random.random((2,12))) 
hs

array([[6., 2., 5., 9., 4., 6., 5., 7., 6., 0., 7., 9.],
       [2., 1., 6., 6., 0., 8., 9., 2., 5., 4., 4., 4.]])

In [55]:
# Split a into 3
hsp = np.hsplit(hs,3)
hsp

[array([[6., 2., 5., 9.],
        [2., 1., 6., 6.]]),
 array([[4., 6., 5., 7.],
        [0., 8., 9., 2.]]),
 array([[6., 0., 7., 9.],
        [5., 4., 4., 4.]])]

In [56]:
hsp[2]

array([[6., 0., 7., 9.],
       [5., 4., 4., 4.]])

## Linear Algebra:

In [57]:
la = np.array([[1.0, 2.0], [3.0, 4.0]])
print(la)

[[1. 2.]
 [3. 4.]]


In [58]:
la.transpose()

array([[1., 3.],
       [2., 4.]])

In [59]:
np.linalg.inv(la)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [60]:
# unit 2x2 matrix; "eye" represents "I"
I = np.eye(2) 
I

array([[1., 0.],
       [0., 1.]])

In [61]:
#Matrix multiplication
M1 = np.array([[1,2],[0,1]])
M2 = np.array([[-1,0],[1,1]])
M1*M2

array([[-1,  0],
       [ 0,  1]])

In [62]:
#The dot product
np.dot(M1,M2)

array([[1, 2],
       [1, 1]])

In [63]:
# trace
np.trace(I)  

np.float64(2.0)

In [64]:
#Solve the system of equations 3 * x0 + x1 = 9 and x0 + 2 * x1 = 8
c0 = np.array([[3,1], [1,2]])
c1 = np.array([9,8])
solve = np.linalg.solve(c0, c1)
solve

array([2., 3.])

In [66]:
#Eigenvalues and eigenvectors
#Eigenvalues are scalar solutions ot the equation Ax = ax, where A is a 2D matrix
#and x is a 1-D vector. Eigenvectors are vectors corresponding to eigenvalues.
A = np.asmatrix("3 -2; 1 0")
A

matrix([[ 3, -2],
        [ 1,  0]])

In [67]:
print("Eigenvalues:\n", np.linalg.eigvals(A))

Eigenvalues:
 [2. 1.]


In [68]:
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues:\n", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Eigenvalues:
 [2. 1.]
Eigenvectors:
 [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


In [70]:
#Singular Value decomposition
B = np.asmatrix("4 11 14; 8 7 -2")
B

matrix([[ 4, 11, 14],
        [ 8,  7, -2]])

In [71]:
#Singular Value Decomposition:
# is a type of factorization that decomposes a matrix into a product of 3 matrices.
U, Sigma, V = np.linalg.svd(B, full_matrices=False) # reduced SVD
#full_matrices : bool, optional
#If True (default), u and v have the shapes (M, M) and (N, N), respectively.
#Otherwise, the shapes are (M, K) and (K, N), respectively, where K = min(M, N).

In [72]:
print("U:\n", U)
print("Sigma:\n", Sigma)
print("V:\n", V)

U:
 [[-0.9486833  -0.31622777]
 [-0.31622777  0.9486833 ]]
Sigma:
 [18.97366596  9.48683298]
V:
 [[-0.33333333 -0.66666667 -0.66666667]
 [ 0.66666667  0.33333333 -0.66666667]]


In [73]:
print("Product:\n", U * np.diag(Sigma) * V)

Product:
 [[ 4. 11. 14.]
 [ 8.  7. -2.]]


## Reference:

https://docs.scipy.org/doc/numpy-dev/user/quickstart.html